version: '3.7'

networks:
  redis-cluster-net:
    external:
      name: redis-cluster-net

services:
  # redis_standalone配置
  redis_standalone:
    image: redis:7.0.9-bullseye
    container_name: redis_standalone
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 192.168.200.91
    ports:
      - 6379:6379
