# 使用帶有 Lua 的 Nginx 基礎映像
FROM fabiocicerchia/nginx-lua

# 安裝開發工具和 luarocks
RUN apk update && \
    apk add --no-cache build-base luarocks && \
    luarocks install lua-cjson


# 複製配置文件到容器中
COPY ./data0/nginx.conf /etc/nginx/nginx.conf
COPY ./data0/lua/rabbitmqstomp.lua /etc/nginx/lua/rabbitmqstomp.lua
COPY ./data0/lua/init_worker.lua /etc/nginx/lua/init_worker.lua
COPY ./data0/lua/enqueue.lua /etc/nginx/lua/enqueue.lua

