version: '3.1'
services:
    nginx:
       build:
         dockerfile: Dockerfile.txt #基於Dockerfile建立image
       volumes:
        - ./data0/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./data0/lua/rabbitmqstomp.lua:/etc/nginx/lua/rabbitmqstomp.lua:ro  # 掛載lua腳本 rabbitmqstomp.lua
        - ./data0/lua/init_worker.lua:/etc/nginx/lua/init_worker.lua:ro  # 掛載lua腳本 init_worker.lua
        - ./data0/lua/enqueue.lua:/etc/nginx/lua/enqueue.lua:ro  # 掛載lua腳本 enqueue.lua



       networks:
        - redis-cluster-net
       ports:
        - "80:80"               
networks:
    redis-cluster-net:
        external: true
        name: redis-cluster-net
